export default {
	LOGIN_START      : 'LOGIN_START',
	LOGIN_SUCCESS    : 'LOGIN_SUCCESS',
	LOGIN_FAILURE    : 'LOGIN_FAILURE',
	REGISTER_START   : 'REGISTER_START',
	REGISTER_SUCCESS : 'REGISTER_SUCCESS',
	REGISTER_FAILURE : 'REGISTER_FAILURE',
};
